name: Dependency Check (Docker + Safe Exit)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create report output directory
        run: mkdir -p dependency-check-report

      - name: Run Dependency-Check using Docker (no fail on CVEs)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -e NVD_API_KEY=$NVD_API_KEY \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check \
            --project "Mi-Proyecto" \
            --scan /src \
            --format "HTML" \
            --out /src/dependency-check-report \
            --nvdApiKey $NVD_API_KEY \
            --failOnCVSS 11

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
